### ISSUE TITLE
Missing dependency cryptography

### ISSUE THREAD

**Issue by ghost** [wontfix-org/tues#5]
paramiko needs cryptography but is not installed when installing tues (with python setup.py develop):
```
$ :~/tues$ tues-provider-fm 
Traceback (most recent call last):
  File "/home/jh/.virtualenvs/solute/bin/tues-provider-fm", line 4, in <module>
    __import__('pkg_resources').require('tues==1.1.2')
  File "/home/jh/.virtualenvs/solute/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/home/jh/.virtualenvs/solute/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/home/jh/.virtualenvs/solute/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/jh/.virtualenvs/solute/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/home/jh/.virtualenvs/solute/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jh/.virtualenvs/solute/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography>=1.1' distribution was not found and is required by paramiko
```

**Comment by mbra** [comment]
Sorry for the inconvenience, but the source of this kind of error is, sadly, not under our control.
I can setup tues in a fresh virtualenv just fine with either `pip install` or `setup.py develop`.

The only way I would suspect this to break is missing development headers for libssl (libssl-dev on debian), but even without those, that should have triggered an error during installation and the tues binaries should not end up in you PATH afterwards.

As is evident from the exception, some package has declared a dependency on `cryptography`, I do not think python ignored the dependency during installation (it rarely failes in that stage at demanding the correct dependencies). It is more likely that the package got either uninstalled later or the virtualenv got messed up somehow. :-(

Could you try running `python setup.py develop` again? Does that fix the problem? Also you are not using the most recent tues Version, if just running `develop` does not work, perhaps pulling and trying again will do the trick (although I doubt it. :-/).

**Comment by mbra** [comment]
It seems the state of the python packaging infrastructure is in worse shape than I thought. A failed `python setup.py develop` run will indeed add the binaries to your path even when installation of the dependencies fails. This is very disappointing but still nothing we could cope with from the tues side.
